language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    receipients:
    - vinc3nt86@hotmail.com
    on_success: change
    on_failure: change

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://vincentgoay.github.io/assessment/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/assessment
  on:
    branch: master
